/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "geometrie.h"

int *
surface_rectangle_1_svc(rectangle *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

rectangle *
creer_rectangle_1_svc(coordonnees *argp, struct svc_req *rqstp)
{
	static rectangle  result;

	/*
	 * insert server code here
	 */

	return &result;
}

booleen *
inclus_1_svc(param_inclus *argp, struct svc_req *rqstp)
{
	static booleen  result;

	/*
	 * insert server code here
	 */

	return &result;
}
